import type { AlgoContext, AlgoMeta, AlgoStep } from './types'
import {
  bellmanFord,
  bfsTraversal,
  cycleDetection,
  dfsTraversal,
  dijkstra,
  floydWarshall,
  kruskalMST,
  primMST,
  spfa,
  tarjanSCC,
  topologicalSort,
} from './basic'
import { boundedFlow, dinic, hlpp, isap, minCut, mpm, sspMinCostFlow } from './flow'
import { hungarianMatching, minVertexCover } from './matching'

export interface AlgoEntry extends AlgoMeta {
  params: ('source' | 'target')[]
  run: (ctx: AlgoContext) => Generator<AlgoStep>
}

export const ALGORITHMS: AlgoEntry[] = [
  {
    id: 'bfs',
    name: 'BFS 遍历',
    category: '遍历',
    params: [],
    run: bfsTraversal,
  },
  {
    id: 'dfs',
    name: 'DFS 遍历',
    category: '遍历',
    params: [],
    run: dfsTraversal,
  },
  {
    id: 'dijkstra',
    name: 'Dijkstra',
    category: '最短路',
    params: ['source'],
    requiresWeights: true,
    hint: '边权重作为距离（未设置按 1）。选择源点后可指定汇点展示路径。',
    run: dijkstra,
  },
  {
    id: 'bellman-ford',
    name: 'Bellman-Ford',
    category: '最短路',
    params: ['source'],
    requiresWeights: true,
    hint: '支持负权边，可检测负环。',
    run: bellmanFord,
  },
  {
    id: 'spfa',
    name: 'SPFA',
    category: '最短路',
    params: ['source'],
    requiresWeights: true,
    hint: '队列优化的 Bellman-Ford，支持负权，可检测负环。',
    run: spfa,
  },
  {
    id: 'floyd',
    name: 'Floyd-Warshall',
    category: '最短路',
    params: [],
    requiresWeights: true,
    hint: '全源最短路，结果以矩阵弹窗展示。',
    run: floydWarshall,
  },
  {
    id: 'prim',
    name: 'Prim MST',
    category: '最小生成树',
    params: ['source'],
    requiresWeights: true,
    hint: '边权重作为边长（未设置按 1），可指定起点。',
    run: primMST,
  },
  {
    id: 'kruskal',
    name: 'Kruskal MST',
    category: '最小生成树',
    params: [],
    requiresWeights: true,
    hint: '按边权排序贪心合并（并查集）。',
    run: kruskalMST,
  },
  {
    id: 'cycle',
    name: '环检测',
    category: '结构',
    params: [],
    hint: 'DFS 三色法，检测图中是否存在环。',
    run: cycleDetection,
  },
  {
    id: 'topo',
    name: '拓扑排序',
    category: '结构',
    params: [],
    hint: 'Kahn 算法，需要图切换为有向图。',
    run: topologicalSort,
  },
  {
    id: 'tarjan',
    name: 'Tarjan SCC',
    category: '结构',
    params: [],
    hint: '求强连通分量并同色标注，需要图切换为有向图。',
    run: tarjanSCC,
  },
  {
    id: 'dinic',
    name: 'Dinic 最大流',
    category: '网络流',
    params: ['source', 'target'],
    requiresCapacity: true,
    hint: '边 capacity 为容量（未设置按 1）。选择源点与汇点。',
    run: dinic,
  },
  {
    id: 'isap',
    name: 'ISAP 最大流',
    category: '网络流',
    params: ['source', 'target'],
    requiresCapacity: true,
    hint: '距离标号 + gap 优化。选择源点与汇点。',
    run: isap,
  },
  {
    id: 'mpm',
    name: 'MPM 最大流',
    category: '网络流',
    params: ['source', 'target'],
    requiresCapacity: true,
    hint: '潜势瓶颈算法。选择源点与汇点。',
    run: mpm,
  },
  {
    id: 'hlpp',
    name: 'HLPP 预流推进',
    category: '网络流',
    params: ['source', 'target'],
    requiresCapacity: true,
    hint: '最高标号预流推进 + gap 优化，节点上方显示溢出量。选择源点与汇点。',
    run: hlpp,
  },
  {
    id: 'ssp',
    name: '费用流 SSP',
    category: '网络流',
    params: ['source', 'target'],
    requiresCapacity: true,
    requiresWeights: true,
    hint: '边 cost 为费用（未设置按 0），capacity 为容量。选择源点与汇点。',
    run: sspMinCostFlow,
  },
  {
    id: 'bounded',
    name: '上下界流',
    category: '网络流',
    params: ['source', 'target'],
    requiresCapacity: true,
    requiresWeights: true,
    hint: 'weight 为下界，capacity 为上界。选择源汇求有源汇上下界最大流；不选则求无源汇循环可行流。',
    run: boundedFlow,
  },
  {
    id: 'mincut',
    name: '最小割',
    category: '网络流',
    params: ['source', 'target'],
    requiresCapacity: true,
    hint: '基于最大流残量网络划分割集，割边标红。选择源点与汇点。',
    run: minCut,
  },
  {
    id: 'hungarian',
    name: '匈牙利匹配',
    category: '匹配',
    params: [],
    hint: '二分图最大匹配，自动按 BFS 染色划分左右部。',
    run: hungarianMatching,
  },
  {
    id: 'vertex-cover',
    name: '最小点覆盖',
    category: '匹配',
    params: [],
    hint: 'König 定理：最小点覆盖大小 = 最大匹配数，覆盖节点标红。',
    run: minVertexCover,
  },
]

export const ALGO_CATEGORIES: string[] = ['遍历', '最短路', '最小生成树', '结构', '网络流', '匹配']
