import type { AlgoCategory, AlgoContext, AlgoMeta, AlgoStep } from './types'
import {
  bellmanFord,
  bfsTraversal,
  cycleDetection,
  dfsTraversal,
  dijkstra,
  floydWarshall,
  kruskalMST,
  primMST,
  spfa,
  tarjanSCC,
  topologicalSort,
} from './basic'
import { boundedFlow, dinic, hlpp, isap, minCut, mpm, sspMinCostFlow } from './flow'
import { hungarianMatching, minVertexCover } from './matching'

export interface AlgoEntry extends AlgoMeta {
  params: ('source' | 'target')[]
  run: (ctx: AlgoContext) => Generator<AlgoStep>
}

export const ALGORITHMS: AlgoEntry[] = [
  {
    id: 'bfs',
    nameKey: 'algo.bfs',
    category: 'cat.traverse',
    params: [],
    run: bfsTraversal,
  },
  {
    id: 'dfs',
    nameKey: 'algo.dfs',
    category: 'cat.traverse',
    params: [],
    run: dfsTraversal,
  },
  {
    id: 'dijkstra',
    nameKey: 'algo.dijkstra',
    category: 'cat.shortest',
    params: ['source'],
    requiresWeights: true,
    hintKey: 'algo.hint.dijkstra',
    run: dijkstra,
  },
  {
    id: 'bellman-ford',
    nameKey: 'algo.bellmanFord',
    category: 'cat.shortest',
    params: ['source'],
    requiresWeights: true,
    hintKey: 'algo.hint.bellmanFord',
    run: bellmanFord,
  },
  {
    id: 'spfa',
    nameKey: 'algo.spfa',
    category: 'cat.shortest',
    params: ['source'],
    requiresWeights: true,
    hintKey: 'algo.hint.spfa',
    run: spfa,
  },
  {
    id: 'floyd',
    nameKey: 'algo.floyd',
    category: 'cat.shortest',
    params: [],
    requiresWeights: true,
    hintKey: 'algo.hint.floyd',
    run: floydWarshall,
  },
  {
    id: 'prim',
    nameKey: 'algo.prim',
    category: 'cat.mst',
    params: ['source'],
    requiresWeights: true,
    hintKey: 'algo.hint.prim',
    run: primMST,
  },
  {
    id: 'kruskal',
    nameKey: 'algo.kruskal',
    category: 'cat.mst',
    params: [],
    requiresWeights: true,
    hintKey: 'algo.hint.kruskal',
    run: kruskalMST,
  },
  {
    id: 'cycle',
    nameKey: 'algo.cycle',
    category: 'cat.structure',
    params: [],
    hintKey: 'algo.hint.cycle',
    run: cycleDetection,
  },
  {
    id: 'topo',
    nameKey: 'algo.topo',
    category: 'cat.structure',
    params: [],
    hintKey: 'algo.hint.topo',
    run: topologicalSort,
  },
  {
    id: 'tarjan',
    nameKey: 'algo.tarjan',
    category: 'cat.structure',
    params: [],
    hintKey: 'algo.hint.tarjan',
    run: tarjanSCC,
  },
  {
    id: 'dinic',
    nameKey: 'algo.dinic',
    category: 'cat.flow',
    params: ['source', 'target'],
    requiresCapacity: true,
    hintKey: 'algo.hint.dinic',
    run: dinic,
  },
  {
    id: 'isap',
    nameKey: 'algo.isap',
    category: 'cat.flow',
    params: ['source', 'target'],
    requiresCapacity: true,
    hintKey: 'algo.hint.isap',
    run: isap,
  },
  {
    id: 'mpm',
    nameKey: 'algo.mpm',
    category: 'cat.flow',
    params: ['source', 'target'],
    requiresCapacity: true,
    hintKey: 'algo.hint.mpm',
    run: mpm,
  },
  {
    id: 'hlpp',
    nameKey: 'algo.hlpp',
    category: 'cat.flow',
    params: ['source', 'target'],
    requiresCapacity: true,
    hintKey: 'algo.hint.hlpp',
    run: hlpp,
  },
  {
    id: 'ssp',
    nameKey: 'algo.ssp',
    category: 'cat.flow',
    params: ['source', 'target'],
    requiresCapacity: true,
    requiresWeights: true,
    hintKey: 'algo.hint.ssp',
    run: sspMinCostFlow,
  },
  {
    id: 'bounded',
    nameKey: 'algo.bounded',
    category: 'cat.flow',
    params: ['source', 'target'],
    requiresCapacity: true,
    requiresWeights: true,
    hintKey: 'algo.hint.bounded',
    run: boundedFlow,
  },
  {
    id: 'mincut',
    nameKey: 'algo.mincut',
    category: 'cat.flow',
    params: ['source', 'target'],
    requiresCapacity: true,
    hintKey: 'algo.hint.mincut',
    run: minCut,
  },
  {
    id: 'hungarian',
    nameKey: 'algo.hungarian',
    category: 'cat.matching',
    params: [],
    hintKey: 'algo.hint.hungarian',
    run: hungarianMatching,
  },
  {
    id: 'vertex-cover',
    nameKey: 'algo.vertexCover',
    category: 'cat.matching',
    params: [],
    hintKey: 'algo.hint.vertexCover',
    run: minVertexCover,
  },
]

export const ALGO_CATEGORIES: AlgoCategory[] = ['cat.traverse', 'cat.shortest', 'cat.mst', 'cat.structure', 'cat.flow', 'cat.matching']
